---
title: "moex_new"
author: "ditiatev"
date: "21 07 2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

# Setup
```{r setup, include=FALSE}
options(digits = 4)
options(scipen = 999)

library(statsr)
library(plyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(reshape2)
library(BAS)
library(GGally)
library(FNN)
library(BayesFactor)
library(gridExtra)
library(foreach)
library(doParallel)

source("./scripts/bayes/bayes_inference.R")
source("./scripts/bayes/bayes_util.R")
source("./scripts/bayes/bayes_single_mean_JZS.R")
source("./scripts/bayes/bayes_two_mean.R")

source("./scripts/saveGGplot.r")
source("./scripts/opendir.r")
source("./scripts/makePrColForStrategy.r")
source("./scripts/get_workset.R")
source("./scripts/get_NormalDistForvard.r")
source("./scripts/get_NormalDist.r")
source("./scripts/get_df_unique_variabels.r")
source("./scripts/get_separate_index.r")
source("./scripts/get_df_unique_variabels.r")
source("./scripts/convert_l_var_to_df_var.r")
#source("./scripts/normalizeXtrainXtest.R")
source("./scripts/create_X_y.R")
source("./scripts/paste_summary.R")
source("./scripts/create_vector_dates.R")
source("./scripts/get_sample_date_index.R")
source("./scripts/get_separate_index.r")
source("./scripts/get_primary_summary.r")
source("./scripts/get_vote_summary_parallel.r")
source("./scripts/get_vote_train_summary_parallel.r")
source("./scripts/create_lxy_train1_train2.r")
source("./scripts/culculate_NPV.r")
source("./scripts/get_topVars.r")
source("./scripts/get_df_best_n_by_npv.r")
source("./scripts/get_df_lev4.r")
source("./scripts/get_cumulative_profit.r")
source("./scripts/paste_primary_summary_parallel.r")
source("./scripts/count_lev3.r")
source("./scripts/get_level_value.r")
```


```{r}
get_nona_variables <- function(df_NA, start_date = ymd('20190101'), end_date = ymd('20200401')) {
  vVariables <- unique(names(df_NA))
  vVariables <- vVariables[which(vVariables != 'date')]
  index <- which((df_NA$date > start_date) & (df_NA$date < end_date))
  
  l_topVars_NA <- list()
for (vTopVar in vVariables) {
  n_NA <- sum(is.na(df_NA[index,vTopVar]))
  l_topVars_NA[vTopVar] <- n_NA
}
df_topVars_NA <- data.frame('n_NA' = do.call(rbind,l_topVars_NA))
df_topVars_NA$Var <- rownames(df_topVars_NA)
index <- (df_topVars_NA$n_NA < 50)

vVariables <- df_topVars_NA[index,'Var']
}
```

# Data

```{r}
df_strategy <- read.csv("./data/strategy/strategy.csv",
                        colClasses = c("factor","POSIXct","numeric","integer", "factor",
                                       rep("numeric",6),rep("factor",3)))

vStrategiesAll <- unique(df_strategy$strategy)
vStrategies <- as.character(vStrategiesAll[20])
```

```{r, warning=FALSE, message=FALSE}
df_profit_total <- get_WorkSet(vStrategies)
vVariables <- get_nona_variables(df_profit_total)

# vColNames <- c('entryprice','exitprice',
#                'value_IMOEX','value_MOEX10','value_MOEXFN','value_RTSI',
#                'capitalization_RTSI','capitalization_RTSTR','capitalization_RTSTRN','capitalization_RTSTRR')
# df_level <- get_level_value(df_profit_total,vColNames)
# df_profit_total[,paste0(vColNames,'_level')] <- df_level

#vColNames_level <- paste0(vColNames,'_level')
vColNames <- c('value_IMOEX','value_MOEX10','value_MOEXFN','value_RTSI',
               'capitalization_RTSI','capitalization_RTSTR','capitalization_RTSTRN','capitalization_RTSTRR',
               "diffHL_IMOEX","diffOC_IMOEX","diffOL_IMOEX","diffHO_IMOEX",
               "diffHL_MOEX10","diffOC_MOEX10","diffOL_MOEX10","diffHO_MOEX10",
               "diffHL_MOEXFN","diffOC_MOEXFN","diffOL_MOEXFN","diffHO_MOEXFN",
               "diffHL_RTSI","diffOC_RTSI","diffOL_RTSI","diffHO_RTSI")
df_moex_previous <- get_NormalDist(df_daily = df_profit_total,
                                   vColName = vColNames,
                                   sliding_depth = 50, 
                                   slidind_return = c(10,25,50))
df_moex_previous$date <- df_profit_total$date

#df_moex_previous <- readRDS(paste0('./data/vote/df_moex.rds'))
```

Previos MA by vColNames
```{r, warning=FALSE, message=FALSE}
knn_k <- 90
for (vStrategy in vStrategies) {
  # data
  # df_profit <- get_WorkSet(vStrategy)
  df_profit_total <- get_WorkSet(vStrategy)
  df_profit_total <- df_profit_total[,1:11]
  # vColNames <- c('entryprice','exitprice')
  # df_level <- get_level_value(df_profit_total,vColNames)
  # df_profit_total[,vColNames] <- df_level

  start_date <- dmy('01012017')
  stop_date <- min(c(max(df_profit_total$date),max(df_moex_previous$date)))

l_str_save <- list()

#dates_iteration_index <- which(df_profit_total$date > l_str_save$work_date)
dates_iteration_index <- which(df_profit_total$date > start_date)
for (date_iteration_index in dates_iteration_index) {

# start
if (is.null(l_str_save['stratagy_name'][[1]])) {
  l_str_save['stratagy_name'] <- vStrategy
}

###########
###########
# df_profit
###########

if (is.null(l_str_save['df_profit'][[1]])) {
  # code to get whole df
  df_profit <- df_profit_total[df_profit_total$date < start_date,]
  l_str_save['df_profit'] <- list(df_profit)
  
  # make pr colums
  vColNames_profit <- colnames(df_profit)[c(3:4,6:11)]
  df_profit_previous <- get_NormalDist(df_daily = df_profit, 
                                       vColName = vColNames_profit,
                                       sliding_depth = 50, 
                                       slidind_return = c(10,25,50))
  l_str_save['df_profit_previous'] <- list(df_profit_previous)
  
  # make forvard profit
  df_profit_forvard <- get_NormalDistForvard(df_daily = df_profit, 
                                             vColName = 'profit', 
                                             sliding_depth = 50)[,1:49]
  df_profit_forvard$date <- df_profit$date
  l_str_save['df_profit_forvard'] <- list(df_profit_forvard)
  
  # date update
  l_str_save['last_work_date'] <- list(start_date-1)
  l_str_save['work_date'] <- list(max(df_profit_total[df_profit_total$date < start_date,'date'])[[1]])
} else {
  # date update
  last_work_date <- max(l_str_save$df_profit$date)
  l_str_save['last_work_date'] <- list(last_work_date)
  
  # code to get df_profit for next date
  df_profit_next <- head(df_profit_total[df_profit_total$date >= last_work_date,],2)
  df_profit_next[2,3:11] <- NA
  nrow_df_profit <- nrow(l_str_save$df_profit)
  df_profit <- rbind(l_str_save$df_profit[1:(nrow_df_profit-1),],df_profit_next)
  l_str_save['df_profit'] <- list(df_profit)
  
  # make pr colums
  df_profit_previous <- get_NormalDist(df_daily = tail(df_profit,51),
                                       vColName = vColNames_profit,
                                       sliding_depth = 50, 
                                       slidind_return = c(10,25,50))
  df_profit_previous <- rbind(l_str_save$df_profit_previous,tail(df_profit_previous,1))
  l_str_save['df_profit_previous'] <- list(df_profit_previous)
  
  # make forvard profit
  df_profit_forvard <- get_NormalDistForvard(df_daily = tail(df_profit,51),
                                             vColName = 'profit', 
                                             sliding_depth = 50)[,1:49]
  df_profit_forvard$date <- tail(df_profit,51)$date
  n_row <- nrow(l_str_save$df_profit_forvard)
  df_profit_forvard <- rbind(l_str_save$df_profit_forvard[1:(n_row-50),],df_profit_forvard)
  l_str_save['df_profit_forvard'] <- list(df_profit_forvard)
  
  # date update
  work_date <- max(df_profit$date)
  l_str_save['work_date'] <- list(work_date)
}

df_profitPrAll <- do.call(cbind,list(data.frame('profit' = l_str_save$df_profit$profit),
                                     l_str_save$df_profit_previous,
                                     l_str_save$df_profit_forvard))

df_profitPrAll <- merge(df_profitPrAll, df_moex_previous, by = 'date', all.x = T)
###########

###########
###########
# Variables
###########

vVariables <- unique(c(colnames(l_str_save$df_profit_previous),
                       colnames(df_moex_previous)))
vVariables <- vVariables[which(vVariables != 'date')]

if (is.null(l_str_save['vVariables'][[1]])) {
  l_str_save['vVariables'] <- list(vVariables)
} else {
  newVariables <- setdiff(vVariables, l_str_save$vVariables)
  l_str_save['newVariables'] <- list(newVariables)
}

##########

##########
##########
## df_topVars
##########
if (is.null(l_str_save['l_topVars'][[1]])) {
  df_unique_variabels <- get_df_unique_variabels(vVariables)
  df_profit_forvard <- l_str_save$df_profit_forvard
  topVars_date <- start_date
  l_topVars <- list()
  l_str_save['topVars_date'] <- list(topVars_date)
  
  vProfitsNext <- c(3,4,5,6)
        for (vProfitNext in vProfitsNext) {
                
                df_profitPr <- df_profitPrAll
                df_profitPr[,'profit'] <- df_profit_forvard[,paste0('profit_mean_Next_',vProfitNext)]
                df_profitPr$date <- ymd(df_profitPr$date)
                
                l_vars <- list()
                vSizeGroup <- 1000
                nGroups <- ceiling(nrow(df_unique_variabels)/vSizeGroup)
                index <- df_profitPr$date < topVars_date
                for (n_group in 1:nGroups) {
                        
                        startindex <- ((n_group-1)*vSizeGroup)
                        endindex <- ((n_group*vSizeGroup)-1)
                        if (endindex > nrow(df_unique_variabels)) {
                                endindex <- nrow(df_unique_variabels)
                        }
                        df_unique_variabels_selected <- df_unique_variabels[startindex:endindex,]
                        #undebug(paste_primary_summary_parallel)
                        l_var_parallel <- paste_primary_summary_parallel(date = topVars_date,
                                                                         df_variabels = df_unique_variabels_selected,
                                                                         df_profit = df_profitPr[index,],
                                                                         paralleling = TRUE,
                                                                         knn_k = knn_k)
                        l_vars[length(l_vars)+1] <- list(convert_l_var_to_df_var(l_var = l_var_parallel))
                        df_unique_variabels[startindex:endindex,'calculated'] <- 1
                }
                
                # Shoose varibels
                df_topVars <- get_topVars(l_vars = l_vars,quan_min_max = 0.7,quan_min_max_scater = 0.7)
                l_topVars[as.character(vProfitNext)] <- list(df_topVars)
        }
  l_str_save['l_topVars'] <- list(l_topVars)
}
###########

##########
##########
## Lev1
##########
if (is.null(l_str_save['l_lev1'][[1]])) {
        l_lev1 <- list()
        ### TRAIN
        l_lev1_train <- list()
        for (topVars_name in names(l_str_save$l_topVars)) {
                df_topVars <- l_str_save$l_topVars[topVars_name][[1]]
                days_lag <- as.numeric(topVars_name)+1
                
                df_profitPr <- df_profitPrAll
                df_profitPr[,'profit'] <- df_profit_forvard[,paste0('profit_mean_Next_',topVars_name)]
                #undebug(get_vote_train_summary_parallel)
                df_vote_train_summary_parallel <- get_vote_train_summary_parallel_new(df_profitPr = df_profitPr,
                                                                                  df_topVars = df_topVars,
                                                                                  date = l_str_save$topVars_date[1],
                                                                                  days_lag = days_lag, paralleling = TRUE,
                                                                                  knn_k = knn_k)
                l_lev1_train[topVars_name] <- list(df_vote_train_summary_parallel)
        }
        
        #source("./scripts/get_vote_train_summary_parallel.r")
        # empty space at the end of train periods
        work_date <- l_str_save$work_date
        last_train_date <- max(l_lev1_train[[tail(names(l_lev1_train),1)]]$date)
        last_train_date_index <- which((l_str_save$df_profit$date >= last_train_date) &
                                         (l_str_save$df_profit$date < work_date))
        
        l_lev1_train_empty_date <- list()
        for (train_date_index in last_train_date_index) {
          l_str_save$work_date <- l_str_save$df_profit[train_date_index,"date"]
          l_lev1_train_empty_date[as.character(train_date_index)] <- 
            list(get_vote_summary_parallel(df_profitPr = df_profitPrAll, l_str_save = l_str_save, knn_k = knn_k))
          }
        df_lev1_train_empty_date <- do.call(rbind,l_lev1_train_empty_date)
        l_str_save$work_date <- work_date
        
        # merge train
        for (name_lev1 in names(l_lev1_train) ) {
          df_lev1_train <- l_lev1_train[[name_lev1]]
          col_names <- colnames(df_lev1_train)
          index_empty <- which(df_lev1_train_empty_date$MA == name_lev1)
          df_lev1_train_empty <- df_lev1_train_empty_date[index_empty,col_names]
          
          index_full <- setdiff(as.character(df_lev1_train$date), as.character(df_lev1_train_empty$date))
          rownames(df_lev1_train) <- as.character(df_lev1_train$date)
          df_lev1_train <- rbind(df_lev1_train[index_full,],df_lev1_train_empty)
          l_lev1_train[[name_lev1]] <- df_lev1_train
        }
        l_lev1['train'] <- list(l_lev1_train)
        
        ### TEST
        #undebug(get_vote_summary_parallel)
        l_lev1_test <- list(get_vote_summary_parallel(df_profitPr = df_profitPrAll,
                                                      l_str_save = l_str_save, paralleling = TRUE, 
                                                      knn_k = knn_k))
        l_lev1['test'] <- l_lev1_test
        
        ### UPDATE
        l_str_save['l_lev1'] <- list(l_lev1)
} else {
  last_test_date <- max(l_str_save$l_lev1$test$date)
  if (l_str_save$work_date != last_test_date) {
    #undebug(get_vote_summary_parallel)
    df_lev1_test <- get_vote_summary_parallel(df_profitPr = df_profitPrAll,
                                              l_str_save = l_str_save, paralleling = TRUE,
                                              knn_k = knn_k)
    l_str_save$l_lev1$test <- rbind(l_str_save$l_lev1$test,df_lev1_test)
  }
}

##########

##########
##########
## Lev2
##########
if (is.null(l_str_save['l_lev2'][[1]])) {
        l_lev2 <- list()
        # train
        l_lev2_train <- list()
        for (lev1_name in names(l_str_save$l_lev1$train)) {
                # df
                df_lev1 <- l_str_save$l_lev1$train[lev1_name][[1]]
                v_profit_next_name <- paste0('profit_mean_Next_',lev1_name)
                df_forvard <- l_str_save$df_profit_forvard[,c("date",v_profit_next_name)]
                names(df_forvard) <- c('date','profit')
                df_lev1 <- merge(df_lev1, df_forvard, by = 'date', all.x = T)
                
                ## TrainPred
                vVars = c('prob0_up','prob0_up_sd','scater_prob0_up')
                #undebug(create_lxy_train1_train2)
                lxy_train <- create_lxy_train1_train2(df_profitPr = df_lev1,
                                                      date = l_str_save$topVars_date, 
                                                      vVars = vVars)
                
                profit_pred_1  <- knn.reg(train=lxy_train$l_train_1$X_train,
                                          y=lxy_train$l_train_1$y_train,
                                          test=lxy_train$l_train_1$X_test,
                                          k=10)[['pred']]
                profit_pred_2  <- knn.reg(train=lxy_train$l_train_2$X_train,
                                          y=lxy_train$l_train_2$y_train,
                                          test=lxy_train$l_train_2$X_test,
                                          k=10)[['pred']]
                
                df_lev2_train <- data.frame('date' = c(lxy_train$l_train_1$date_test,
                                                       lxy_train$l_train_2$date_test),
                                            'profit_pred' = c(profit_pred_1,
                                                              profit_pred_2))
                l_lev2_train[lev1_name] <- list(df_lev2_train)
                
        }
        l_lev2['train'] <- list(l_lev2_train)
        
        # test
        l_lev2_test <- list()
        for (lev1_name in names(l_str_save$l_lev1$train)) {
                # df
                df_lev1_train <- l_str_save$l_lev1$train[lev1_name][[1]]
                df_lev1_test  <- l_str_save$l_lev1$test
                index_test_lev1 <- which(df_lev1_test$MA == lev1_name)
                # df_lev1_test <- df_lev1_test[index_test_lev1,c('date','prob0_up_sd','prob0_down_sd','scater_prob0_up',
                #                                                'scater_prob0_down','prob0_up','prob0_down','n')]
                df_lev1_test <- df_lev1_test[index_test_lev1,names(df_lev1_train)]
                df_lev1 <- rbind(df_lev1_train,df_lev1_test)
                vVars = c('prob0_up','prob0_up_sd','scater_prob0_up')
                df_lev1 <- df_lev1[,c('date',vVars)]
                v_profit_next_name <- paste0('profit_mean_Next_',lev1_name)
                df_forvard <- l_str_save$df_profit_forvard[,c("date",v_profit_next_name)]
                names(df_forvard) <- c('date','profit')
                df_lev1 <- merge(df_lev1, df_forvard, by = 'date', all.x = T)
                df_lev1[sapply(df_lev1, is.nan)] <- NA
                df_lev1[sapply(df_lev1, is.infinite)] <- NA
                # prediction
                index_train <- ((df_lev1$date < l_str_save$work_date) & (complete.cases(df_lev1)))
                index_predict <- which((df_lev1$date == l_str_save$work_date) & (complete.cases(df_lev1[,c(vVars)])))
                #debug(create_X_y)
                l <- create_X_y(df = df_lev1,
                                train_index = index_train,
                                test_index = index_predict,
                                vVars = vVars)
                
                profit_pred  <- knn.reg(train=l$X_train, y=l$y_train, test=l$X_test, k=10)[['pred']]
                l_lev2_test[as.character(lev1_name)] <- list(data.frame('date' = l$date_test,
                                                                        'profit_pred' = profit_pred,
                                                                        'MA' = as.character(lev1_name)))
                
        }
        df_lev2_test <- do.call(rbind,l_lev2_test)
        l_lev2['test'] <- list(df_lev2_test)
        
        l_str_save['l_lev2'] <- list(l_lev2)
} else {
        # test
        l_lev2_test <- list()
        for (lev1_name in names(l_str_save$l_lev1$train)) {
                # df
                df_lev1_train <- l_str_save$l_lev1$train[lev1_name][[1]]
                df_lev1_test  <- l_str_save$l_lev1$test
                index_test_lev1 <- which(df_lev1_test$MA == lev1_name)
                # df_lev1_test <- df_lev1_test[index_test_lev1,c('date','prob0_up_sd','prob0_down_sd','scater_prob0_up',
                #                                                'scater_prob0_down','prob0_up','prob0_down','n')]
                df_lev1_test <- df_lev1_test[index_test_lev1,names(df_lev1_train)]
                df_lev1 <- rbind(df_lev1_train,df_lev1_test)
                vVars = c('prob0_up','prob0_up_sd','scater_prob0_up')
                df_lev1 <- df_lev1[,c('date',vVars)]
                v_profit_next_name <- paste0('profit_mean_Next_',lev1_name)
                df_forvard <- l_str_save$df_profit_forvard[,c("date",v_profit_next_name)]
                names(df_forvard) <- c('date','profit')
                df_lev1 <- merge(df_lev1, df_forvard, by = 'date', all.x = T)
                df_lev1[sapply(df_lev1, is.nan)] <- NA
                df_lev1[sapply(df_lev1, is.infinite)] <- NA
                # prediction
                index_train <- ((df_lev1$date < l_str_save$work_date) & (complete.cases(df_lev1)))
                index_predict <- which((df_lev1$date == l_str_save$work_date) & (complete.cases(df_lev1[,c(vVars)])))
                
                if (length(index_predict) == 0) {
                  l_lev2_test[as.character(lev1_name)] <- list(data.frame('date' = l_str_save$work_date,
                                                                          'profit_pred' = NA,
                                                                          'MA' = as.character(lev1_name)))
                  } else {
                #undebug(create_X_y)
                l <- create_X_y(df = df_lev1,
                                train_index = index_train,
                                test_index = index_predict,
                                vVars = vVars)
                
                profit_pred  <- knn.reg(train=l$X_train, y=l$y_train, test=l$X_test, k=10)[['pred']]
              
                l_lev2_test[as.character(lev1_name)] <- list(data.frame('date' = l$date_test,
                                                                        'profit_pred' = profit_pred,
                                                                        'MA' = as.character(lev1_name)))
                }
                
        }
        
        df_lev2_test <- do.call(rbind,l_lev2_test)
        df_lev2_test <- rbind(l_str_save$l_lev2$test,df_lev2_test)
        l_str_save$l_lev2$test <- df_lev2_test
}
##########

##########
##########
## Lev3
##########
  undebug(count_lev3)
  l_lev3 <- count_lev3(l_str_save = l_str_save)
  l_str_save['df_lev3'] <- list(l_lev3$df_lev3)
  l_str_save['l_npv']   <- list(l_lev3$l_npv)
}

saveRDS(l_str_save, file = paste0("./data/vote/",'debug',l_str_save$stratagy_name,".rds"))
}
```

# lev3
```{r, warning=FALSE, message=FALSE}
source("./scripts/count_lev3.r")
l_str_save['work_date'] <- list(ymd('20170105'))
l_str_save['last_work_date'] <- list(start_date-1)
l_str_save['df_lev3'] <- NULL
l_str_save['l_npv'] <- NULL

l_str_save <- readRDS(paste0("./data/vote/",'debugSL_18_22_RTS_Int01.rds'))
debug(count_lev3)
l_lev3 <- count_lev3(l_str_save = l_str_save,only_workdate = TRUE)
df_lev3 <- l_lev3$df_lev3
```

```{r}
#l_str_save <- readRDS("./data/vote/SL_14_18_RTS_Int005.rds")

l_str_save[['df_lev3']] %>%
 filter(date > start_date, date < ymd('20200401')) %>%
  group_by(vote >= 12, npv >= 0) %>%
  summarise(sum(profit, na.rm = T),n(),mean(npv))
```



```{r, warning=FALSE, message=FALSE}
df_profit_lev3 <- cbind(df_profitPr[,c("date","profit","profit_by_day","profit_pred")],
                        df_profit_lev3)
df_profit_lev3$profit_pred_Pr0 <- df_profit_lev3$profit_pred
df_profit_lev3$year <- year(df_profit_lev3$date)
df_profit_lev3$month <- month(df_profit_lev3$date)

df_train <- df_profit_lev3[which(df_profitPr$date < vDates[1]),]
df_npv <- get_df_best_n_by_npv(df_train = df_train, vProfitNext = vProfitNext)
for (x in 1:nrow(df_npv)) {
  n        <- df_npv[x,"n"]
  lev_prof <- df_npv[x,"lev_prof"]
  npv      <- df_npv[x,"npv"]
  
  v_npv_Name   <- paste0('npv_profit_pred_next_',vProfitNext,'_n_',n)
  v_Pr_n_Names <- paste0('profit_pred', "_Pr", 0:n)
  df_profit_lev3[,'profit_pred'] <- apply(df_profit_lev3[,v_Pr_n_Names], 1, sum, na.rm = T)
  
  traid_index <- (df_profit_lev3$profit_pred > lev_prof)
  df_strategy_vote[,v_npv_Name] <- 0
  df_strategy_vote[traid_index,v_npv_Name] <- npv
}
```








```{r, warning=FALSE, message=FALSE}
vVariables <- vVariables[which(!(vVariables %in% c("date","profit","profit_by_day",
                                                   "best_lev_profit_pred_next_10","profit_pred_next_10")))]
df_unique_variabels <- get_df_unique_variabels(vVariables)
df_unique_variabels <- df_unique_variabels[df_unique_variabels$calculated == 0,]


df_strategy_vote <- df_profit[,c('strategy','date','profit')]

vProfitsNext <- c(20,25,30,35)
for (vProfitNext in vProfitsNext) {
  
df_profitPr <- df_profitPrAll
df_profitPr[,'profit'] <- df_profit_forvard[,paste0('profit_mean_Next_',vProfitNext)]
df_profitPr$date <- ymd(df_profitPr$date)
df_profitPr$profit_by_day <- df_profit$profit

##########
##########
## Vars
##########
l_vars <- list()
vSizeGroup <- 1000
nGroups <- ceiling(nrow(df_unique_variabels)/vSizeGroup)
vDates <- create_vector_dates()
index <- df_profitPr$date < vDates[1]
for (n_group in 1:nGroups) {
  
  startindex <- ((n_group-1)*vSizeGroup)
  endindex <- ((n_group*vSizeGroup)-1)
  if (endindex > nrow(df_unique_variabels)) {
    endindex <- nrow(df_unique_variabels)
  }
  df_unique_variabels_selected <- df_unique_variabels[startindex:endindex,]
  
  l_var_parallel <- paste_primary_summary_parallel(date = vDates[1],
                                                   df_variabels = df_unique_variabels_selected,
                                                   df_profit = df_profitPr[index,])
  l_vars[length(l_vars)+1] <- list(convert_l_var_to_df_var(l_var = l_var_parallel))
  df_unique_variabels[startindex:endindex,'calculated'] <- 1
  #print(n_group/nGroups)
}

# Shoose varibels
df_topVars <- get_topVars(l_vars = l_vars)

####################################################
# Vouting ##########################################
####################################################

##########
##########
## Lev1
##########
vVoteIndex <- which(df_profitPr$date >= vDates[1])
l_vote_summary_parallel <- get_vote_summary_parallel(df_profitPr = df_profitPr,
                                                     df_topVars = df_topVars,
                                                     vVoteIndex = vVoteIndex,
                                                     core = 3,
                                                     days_lag = (vProfitNext+1))
df_vote_test_summary_parallel  <- as.data.frame(do.call(rbind,l_vote_summary_parallel))

df_vote_train_summary_parallel <- get_vote_train_summary_parallel(df_profitPr = df_profitPr,
                                                                  df_topVars = df_topVars,
                                                                  date = vDates[1],
                                                                  days_lag = (vProfitNext+1))

df_vote_summary_parallel <- rbind(df_vote_train_summary_parallel,df_vote_test_summary_parallel)

df_profitPr <- merge(df_profitPr, df_vote_summary_parallel,
                        all.x = TRUE, by.x = c("date"), by.y = c("date"))

df_profitPr$profit_pred <- 0
df_profitPr <- df_profitPr %>%
  arrange(date)
rownames(df_profitPr) <- NULL
##########


##########
##########
## Lev2
##########


## TrainPred
vVars = c('prob0_up','prob0_up_sd','scater_prob0_up')
lxy_train <- create_lxy_train1_train2(df_profitPr = df_profitPr,
                                      date = date, vVars = vVars)

profit_pred_1  <- knn.reg(train=lxy_train$l_train_1$X_train,
                        y=lxy_train$l_train_1$y_train,
                        test=lxy_train$l_train_1$X_test,
                        k=10)[['pred']]
profit_pred_2  <- knn.reg(train=lxy_train$l_train_2$X_train,
                        y=lxy_train$l_train_2$y_train,
                        test=lxy_train$l_train_2$X_test,
                        k=10)[['pred']]

df_train <- data.frame('date' = c(lxy_train$l_train_1$date_test,
                                  lxy_train$l_train_2$date_test),
                       'profit_pred' = c(profit_pred_1,
                                         profit_pred_2))

drops <- c('profit_pred')
df_profitPr <- df_profitPr[ , !(names(df_profitPr) %in% drops)]
df_profitPr <- merge(df_profitPr, df_train, all.x = TRUE, by.x = c("date"), by.y = c("date"))

## TestPred
date <- vDates[1]
test_start_index <- which.min(abs(df_profitPr$date - date))+1
for (x in test_start_index:nrow(df_profitPr)) {
  date <- df_profitPr[x,"date"]
  df <- df_profitPr[c(vVars,'profit','date')]
  df[sapply(df, is.nan)] <- NA
  df <- na.omit(df)
  index_tain <- df$date < (date)
  index_predict <- which(df$date == date)
  if (length(index_predict) == 0) {next}
    
  l <- create_X_y(df = df,
                  train_index = index_tain,
                  test_index = index_predict,
                  vVars = vVars)
  
  knn_test  <- knn.reg(train=l$X_train, y=l$y_train, test=l$X_test, k=10)
  df_profitPr[x,'profit_pred'] <- knn_test[['pred']]
}
##########


##########
##########
## Lev3
##########


df_profitPr$strategy <- "RTS_14_18"
df_profit_lev3 <- makePrColForStrategy(df_strategy = df_profitPr, 
                                       vColNames = 'profit_pred', 
                                       sliding_depth = (vProfitNext-1))
df_profit_lev3 <- cbind(df_profitPr[,c("date","profit","profit_by_day","profit_pred")],
                        df_profit_lev3)
df_profit_lev3$profit_pred_Pr0 <- df_profit_lev3$profit_pred
df_profit_lev3$year <- year(df_profit_lev3$date)
df_profit_lev3$month <- month(df_profit_lev3$date)

df_train <- df_profit_lev3[which(df_profitPr$date < vDates[1]),]
df_npv <- get_df_best_n_by_npv(df_train = df_train, vProfitNext = vProfitNext)
for (x in 1:nrow(df_npv)) {
  n        <- df_npv[x,"n"]
  lev_prof <- df_npv[x,"lev_prof"]
  npv      <- df_npv[x,"npv"]
  
  v_npv_Name   <- paste0('npv_profit_pred_next_',vProfitNext,'_n_',n)
  v_Pr_n_Names <- paste0('profit_pred', "_Pr", 0:n)
  df_profit_lev3[,'profit_pred'] <- apply(df_profit_lev3[,v_Pr_n_Names], 1, sum, na.rm = T)
  
  traid_index <- (df_profit_lev3$profit_pred > lev_prof)
  df_strategy_vote[,v_npv_Name] <- 0
  df_strategy_vote[traid_index,v_npv_Name] <- npv
}
##########
}
l_strategies[vStrategy] <- list(df_strategy_vote)
}
```

```{r}
# source("./scripts/paste_primary_summary.R")
# undebug(paste_primary_summary)
#   l_var_parallel <- paste_primary_summary(date = vDates[1],
#                                           df_variabels = df_unique_variabels_selected,
#                                           df_profit = df_profitPr[index,])
```

# Read l_str_save

```{r, warning=FALSE, message=FALSE}
source("./scripts/count_lev3.r")
vFiles <- list.files("./data/vote/")
l_strategies <- list()
l_df_lev3 <- list()
l_k_topVars <- 
stoplevel <- 0
for(vFile in vFiles) {
  l_str_save <- readRDS(paste0("./data/vote/",vFile))
  df_lev3 <- l_str_save[['df_lev3']]
  df_lev3 <- merge(df_lev3, l_str_save$df_profit[,c("date","position")], by = 'date', all.x = T)
  

  
  
  #debug(count_lev3)
  #l_lev3 <- count_lev3(l_str_save = l_str_save,only_workdate = FALSE)
  #df_lev3 <- l_lev3$df_lev3
  #stoplevel <- stoplevel+1
  df_lev3$strategy <- vFile
  #df_lev3$stoplevel <- stoplevel
  
  if (grepl("m", vFile) == T) {
    df_lev3$type <- 'knn_100'
    } 
  if(grepl("knn_70", vFile) == T)  {
      df_lev3$type <- 'knn_70'
      } 
  if(grepl("knn_80", vFile) == T)  {
        df_lev3$type <- 'knn_80'
        } 
  if(grepl("knn_90", vFile) == T)  {
          df_lev3$type <- 'knn_90'
  }
  if(grepl("10_14", vFile) == T)  {
          df_lev3$type <- '10_14'
  }
   if(grepl("14_18", vFile) == T)  {
          df_lev3$type <- '14_18'
   }
     if(grepl("18_22", vFile) == T)  {
          df_lev3$type <- '18_22'
          }
  l_df_lev3[vFile] <- list(df_lev3)
  l_strategies[vFile] <- list(l_str_save)
  
  
  
}
df_strategies <- do.call(rbind,l_df_lev3)
```









```{r}
vote_level <- 12
df_strategies %>%
 filter(date < ymd('20200401'),
        date > start_date,
        #type == '18_22',
        ) %>%
  mutate(profit_ma = if_else(vote >= vote_level, profit, 0),
         n_ma = if_else(vote >= vote_level, 1, 0)) %>%
  group_by(strategy,
           test = date > start_date,
           position
           #year(date)
           ) %>%
  summarise(#pr = sum(profit, na.rm = T),
            #pr_up = sum(profit_ma, na.rm = T),
            #pr_diff = (pr_up - pr),
            m_pr = round(mean(profit, na.rm = T),4),
            m_pr_up = round(mean(profit_ma, na.rm = T),4),
            m_pr_diff = (m_pr_up - m_pr),
            n(),
            n_ma = sum(n_ma, na.rm = T),
            vote_level)
```

```{r}
vFiles
```

# Plot debuging

```{r}
branch <- "./plots/debug/"
for(vFile in vFiles[2]) {
df_lev1_test <- l_strategies[[vFile]]$l_lev1$test
index <- which(df_lev1_test$MA == "30")

df_lev1_train <- l_strategies[[vFile]]$l_lev1$train$`30`
df_lev1 <- rbind(df_lev1_train, df_lev1_test[index,colnames(df_lev1_train)])


df_profit <- l_strategies[[vFile]]$df_lev3

df_lev2_test <- l_strategies[[vFile]]$l_lev2$test
index <- which(df_lev2_test$MA == "30")
df_lev2_train <- l_strategies[[vFile]]$l_lev2$train$`30`
df_lev2 <- rbind(df_lev2_train, df_lev2_test[index,colnames(df_lev2_train)])

df_ggplot <- merge(df_lev1, df_profit[,c("date","profit",'vote', 'npv')], all.x = T, by = 'date')
df_ggplot <- merge(df_ggplot, df_lev2[,c("date","profit_pred")], all.x = T, by = 'date')

df_ggplot <- df_ggplot %>%
  mutate(profit_cum = if_else(is.na(profit),0,profit),
         profit_pred = if_else(is.na(profit_pred),0,profit_pred),
         profit_l2 = if_else(vote >= 12, profit_cum ,0)) %>%
  mutate(profit_cum = cumsum(profit_cum)) %>%
  mutate(profit_cum_l2 = cumsum(profit_l2))

sGGplot <- df_ggplot %>%
  ggplot() +
  geom_point(aes(x = date, y = profit_cum)) +
  geom_point(aes(x = date, y = profit_cum_l2), color = 'green', alpha = 0.1) +
  geom_point(aes(x = date, y = profit_pred*1000), color = 'brown4', alpha = 0.5) +
  geom_point(aes(x = date, y = prob0_up*100), color = 'blue', alpha = 0.1) +
  geom_point(aes(x = date, y = prob0_up_sd*500), color = 'red', alpha = 0.5) +
  geom_point(aes(x = date, y = vote), color = 'purple', alpha = 0.1) +
  geom_vline(xintercept = start_date) +
  ylim(-100,200) +
  ggtitle(vFile)

print(sGGplot)


saveGGplot(sGGplot,branch,paste0(vFile),width = 1600, height = 1200)
}
opendir(branch)
```
```{r}
df_ggplot_vPred <- get_NormalDist(df_daily = df_ggplot,
                                  vColName = 'prob0_up',
                                  sliding_depth = 20,
                                  slidind_return = c(2,20))[,1:2]
df_ggplot[,'diff'] <- df_ggplot_vPred[,1]-df_ggplot_vPred[,2]

#df_ggplot_debug <- merge(df_ggplot, df_debug_vPred, by = 'date', all.x = T)

df_ggplot %>%
  filter(date < ymd('20200401'),
         date > start_date
         ) %>%
  ggplot() +
  geom_point(aes(x = date, y = vPred*100+100), alpha = 0.5, color = 'blue') +
  geom_point(aes(x = date, y = vote+50), alpha = 0.5) +
  geom_point(aes(x = date, y = profit_cum), alpha = 0.5, color = 'red')

df_ggplot %>%
  filter(date < ymd('20200401'),
         date > start_date,
         diff > 0
         ) %>%
  #group_by(year(date)) %>%
  summarise(sum(profit, na.rm = T))
```

```{r}
names(l_str_save$df_profit_previous)
names(l_str_save$df_profit)
```

```{r}
merge(do.call(cbind,list(l_str_save$df_profit_previous,
                   l_str_save$df_profit_forvard)),
                   df_ggplot,
      by = 'date', all.x = T) %>%
  ggplot() +
  geom_point(aes(x = date, y = MAE_sd_Pr_50), alpha = 0.5, color = 'blue') +
  geom_point(aes(x = date, y = profit_mean_Next_25))
```


```{r}
merge(do.call(cbind,list(l_str_save$df_profit_previous,
                   l_str_save$df_profit_forvard)),
                   df_ggplot,
      by = 'date', all.x = T) %>%
  filter(date < ymd('20200401')) %>%
  ggplot() +
  geom_point(aes(x = profit_mean_Next_25, y = entryprice_mean_Pr_25, color = date > start_date), alpha = 0.5)
```

```{r}
vFiles[2]
```


```{r}
source("./scripts/saveGGplot.r")
branch <- "./plots/vote/"
for(vFile in vFiles[2]) {
  #if(grepl("10_14", vFile) == F)  {next}
  for (vote_level in -12:12) {

df_all <- df_strategies %>%
  filter(strategy == vFile,
         date < ymd('20200401')) %>%
  mutate(lev2 = vote,
         vyear = year(date)) %>%
  mutate(profit_cum = if_else(is.na(profit),0,profit),
         lev2 = if_else(is.na(lev2),0,lev2),
         profit_l2 = if_else(lev2 >= vote_level, profit_cum ,0),
         # profit_l2_pr1 = lag(profit_l2),
         # profit_l2_pr2 = lag(profit_l2_pr1),
         # profit_l2_pr3 = lag(profit_l2_pr2),
         # profit_l2 = if_else((profit_l2_pr1+profit_l2_pr2+profit_l2_pr3) >= -0.4, profit_l2, 0),
         # profit_l2 = if_else(is.na(profit_l2),0,profit_l2)
         ) %>%
  mutate(profit_cum = cumsum(profit_cum),
         lev2_cum = cumsum(lev2),
         profit_cum_l2 = cumsum(profit_l2),
         profit_diff = profit_cum_l2 - profit_cum)

df_test <- df_strategies %>%
  filter(strategy == vFile,
         date < ymd('20200401'),
         date >= start_date) %>%
  mutate(lev2 = vote,
         vyear = year(date)) %>%
  mutate(profit_cum = if_else(is.na(profit),0,profit),
         lev2 = if_else(is.na(lev2),0,lev2),
         profit_l2 = if_else(lev2 >= vote_level, profit_cum ,0)) %>%
  mutate(profit_cum = cumsum(profit_cum),
         lev2_cum = cumsum(lev2),
         profit_cum_l2 = cumsum(profit_l2),
         profit_diff = profit_cum_l2 - profit_cum)

tt_all <- ((length(which(df_all$lev2 >= vote_level))-length(which(df_test$lev2 >= vote_level)))/(nrow(df_all)-nrow(df_test)))*100
tt_test <- length(which(df_test$lev2 >= vote_level))/nrow(df_test)*100

  sGGplot <- ggplot() +
  geom_point(aes(x = date, y = profit_cum), alpha = 0.1, data = df_all) +
  geom_point(aes(x = date, y = profit_diff), color = 'green', alpha = 0.1, data = df_all) +
  geom_point(aes(x = date, y = profit_cum_l2), color = 'blue', alpha = 0.1, data = df_all) +
  geom_vline(xintercept = start_date) +
  geom_point(aes(x = date, y = profit_cum), alpha = 0.1, data = df_test) +
  geom_point(aes(x = date, y = profit_diff), color = 'darkgreen', alpha = 0.1, data = df_test) +
  geom_point(aes(x = date, y = profit_cum_l2), color = 'blue', alpha = 0.1, data = df_test) +
  ggtitle(paste0(vFile,"  Vote level: ",vote_level)) + 
    annotate(geom="text", x=ymd('20110601'), y=100, 
             label=paste0("Train trade time: ",round(tt_all,1),'%')) + 
    annotate(geom="text", x=ymd('20110601'), y=90, 
             label=paste0("Test trade time: ",round(tt_test,1),'%'))

      saveGGplot(sGGplot,branch,paste0(vFile,'_vl_',vote_level),width = 1600, height = 1200)
  }
}
opendir(branch)
```

# Strategy work together

```{r}
vote_level <- 10
df_strategies_m <- df_strategies %>%
  filter(#date < start_date,
    date < ymd('20200401'),
         type == 'mod') %>%
  mutate(npv_up0 = if_else(vote >= vote_level, npv_p, 0)) %>%
  group_by(date) %>%
  mutate(n_up0 = n(),
         sum_npv_up0 = sum(npv_up0)) %>%
  mutate(pers = npv_up0/sum_npv_up0) %>%
  mutate(pers = if_else(is.nan(pers), 0, pers)) %>%
  mutate(pers = if_else(is.na(pers), 0, pers)) %>%
  mutate(money = 0,
         money_m = 0) %>%
  arrange(date, stoplevel) %>%
  mutate(pers_pr = lag(pers),
         pers_next = lead(pers),
         pers_pr = if_else(is.na(pers_pr),pers,pers_pr),
         pers_next = if_else(is.na(pers_next),pers,pers_next),
         pers_all = if_else(pers != 0, pers+pers_pr+pers_next,0),
         sum_pers = sum(pers_all),
         pers = if_else(sum_pers == 0,0, pers_all/sum_pers),
         profit_up0 = if_else(vote >= vote_level, profit, 0)) %>%
  mutate(profit_up0 = if_else(is.na(profit_up0), 0, profit_up0))

vdays <- unique(df_strategies_m$date)
vmoney_m <- 100
vmoney <- 100
doit = TRUE
k = 1

for (vday in vdays) {
  if (vday >= start_date) {
    if (doit == TRUE) {
      vmoney_m <- 100
      vmoney <- 100
      doit = FALSE
    }
  }
  
  index <- df_strategies_m$date == vday
  df_strategies_m[index,'money_m'] <- (k*df_strategies_m[index,'pers']*vmoney_m)*((df_strategies_m[index,"profit"])/100)+
    vmoney_m/nrow(df_strategies_m[index,])
  vmoney_m <- sum(df_strategies_m[index,'money_m'])
  #   index <- df_strategies_m$date == vday
  # df_strategies_m[index,'money_m'] <- (k*vmoney_m/nrow(df_strategies_m[index,]))*((df_strategies_m[index,"profit_up0"])/100)+
  #   vmoney_m/nrow(df_strategies_m[index,])
  # vmoney_m <- sum(df_strategies_m[index,'money_m'])
  
  df_strategies_m[index,'money'] <- (k*vmoney/nrow(df_strategies_m[index,]))*((df_strategies_m[index,"profit"])/100)+
    vmoney/nrow(df_strategies_m[index,])
  vmoney <- sum(df_strategies_m[index,'money'])
}

df_strategies_mm <- df_strategies_m %>%
  group_by(date) %>%
  summarise(money = sum(money),
            money_m = sum(money_m))

gg_train <- df_strategies_mm %>%
  filter(date < start_date) %>%
  ggplot() +
  geom_point(aes(x=date, y = money), color = 'red', alpha = 0.2) +
  geom_point(aes(x=date, y = money_m), color = 'green', alpha = 0.2) +
  ylim(0,500)+
  ggtitle('train')

gg_test <- df_strategies_mm %>%
  filter(date > start_date,
          date < ymd('20200401')) %>%
  ggplot() +
  geom_point(aes(x=date, y = money), color = 'red', alpha = 0.2) +
  geom_point(aes(x=date, y = money_m), color = 'green', alpha = 0.2) +
  ylim(50,120)+
  ggtitle('test')

df_strategies_m %>%
  filter(date < ymd('20200401')) %>%
  filter(pers > 0) %>%
  ggplot() +
  geom_histogram(aes(x=pers))

# df_strategies_m %>%
#   filter(date < ymd('20200401')) %>%
#   filter(pers > 0) %>%
#   ggplot() +
#   geom_point(aes(x=pers, y = profit))

df_strategies_m %>%
  filter(date > start_date,
          date < ymd('20200401')) %>%
  arrange(stoplevel) %>%
  ggplot() +
  geom_point(aes(x = date, y = strategy, size = pers), alpha = 0.2, color = 'green')
  # scale_color_gradient2(midpoint=0, limit = c(-2,2), space = "Lab",
  #                       low="red", mid="white", high="green")

grid.arrange(gg_train, gg_test, ncol = 2)
```





```{r}
df_lev4 <- get_df_lev4(l_strategies = l_strategies, 
                       df_date_lev4 = df_profit[,c('date','profit')], 
                       vTraid_index = 6)
df_lev4 %>%
  group_by(year) %>%
  summarise(traid_index = mean(traid_index),
            profit_model = sum(profit_model),
            profit_avarage = sum(profit_avarage),
            profit_best = sum(profit_SL_14_18_RTS_Int02))

df_lev4 %>%
  group_by(year >= 2017) %>%
  summarise(traid_index = mean(traid_index),
            profit_model = sum(profit_model),
            profit_avarage = sum(profit_avarage),
            profit_best = sum(profit_SL_14_18_RTS_Int02))

get_cumulative_profit(df_lev4 = df_lev4, k = 1)
get_cumulative_profit(df_lev4 = df_lev4, k = 2)
get_cumulative_profit(df_lev4 = df_lev4, k = 3)
get_cumulative_profit(df_lev4 = df_lev4, k = 10)
```

# MoneyCulculation

```{r}
ymax <- max(c(df_lev4[,'money_model'],df_lev4[,'money']), na.rm = T)
gg_train <- df_lev4 %>%
  filter(date < vDates[1]) %>%
  ggplot() +
  geom_point(aes(x = date, y = money), color = 'red', alpha = 0.2) +
  geom_point(aes(x = date, y = money_model), color = 'green', alpha = 0.2) +
  ggtitle('Train')

gg_test <- df_lev4 %>%
  filter(date >= vDates[1]) %>%
  ggplot() +
  geom_point(aes(x = date, y = money), color = 'red', alpha = 0.2) +
  geom_point(aes(x = date, y = money_model), color = 'green', alpha = 0.2) +
  ggtitle('Test')

grid.arrange(gg_train, gg_test, ncol = 2)
```


```{r}

```



```{r}
df_money_by_year <- get_cumulative_profit(df_lev4 = df_lev4)
df_money_by_year
train_index <- df_month_summary$year >= 2017

S = 100000
profit <- df_money_by_year$money
m_0 = mean(profit)
s2_0 = var(profit)
n_0 = length(profit)
v_0 = n_0 - 1

phi = rgamma(S, v_0/2, s2_0*v_0/2)
sigma = 1/sqrt(phi)
mu = rnorm(S, mean=m_0, sd=sigma/(sqrt(n_0)))
Y = rnorm(S, mu, sigma)
Years <- 1/(length(which(Y < 0))/length(Y))
sd_profit <- sd(profit)*Years

df <- data.frame("NPV" = rnorm(S, mu, sigma)*Years
           #"income_mu" = rnorm(S, mean=m_0, sd=sigma/(sqrt(n_0)))*Years
           ) %>%
        mutate(positive = if_else(NPV > 0, T, F))

pers_positive <- length(which(df$positive == T))/nrow(df)
text_positive <- paste0((pers_positive)*100," %")
text_negative <- paste0((1-pers_positive)*100," %")

gg_total_profit <- ggplot(data = df) +
        geom_histogram(aes(x=NPV, fill=positive,color = positive), alpha=.3,bins = 100) +
        xlim(0-sd_profit*6,0+sd_profit*6) +
        ylim(-350,5000)+
        #geom_vline(xintercept = mean(df$NPV), linetype="dotted", size=1.5) +
        geom_text(x=0-sd_profit*3, y=-350, label = text_negative, color = "darkred") +
        geom_text(x=0+sd_profit*3, y=-350, label = text_positive , color = "darkgreen") +
        ggtitle(paste0("NPV distribution with mean = ",round(mean(df$NPV),0)))

S = 100000
profit <- df_money_by_year$money_model
m_0 = mean(profit)
s2_0 = var(profit)
n_0 = length(profit)
v_0 = n_0 - 1

phi = rgamma(S, v_0/2, s2_0*v_0/2)
sigma = 1/sqrt(phi)
mu = rnorm(S, mean=m_0, sd=sigma/(sqrt(n_0)))
Y = rnorm(S, mu, sigma)
Years <- 1/(length(which(Y < 0))/length(Y))
sd_profit <- sd(profit)*Years

df <- data.frame("NPV" = rnorm(S, mu, sigma)*Years
           #"income_mu" = rnorm(S, mean=m_0, sd=sigma/(sqrt(n_0)))*Years
           ) %>%
        mutate(positive = if_else(NPV > 0, T, F))

pers_positive <- length(which(df$positive == T))/nrow(df)
text_positive <- paste0((pers_positive)*100," %")
text_negative <- paste0((1-pers_positive)*100," %")

gg_total_profit_model <- ggplot(data = df) +
        geom_histogram(aes(x=NPV, fill=positive,color = positive), alpha=.3,bins = 100) +
        xlim(0-sd_profit*6,0+sd_profit*6) +
        ylim(-350,5000)+
        #geom_vline(xintercept = mean(df$NPV), linetype="dotted", size=1.5) +
        geom_text(x=0-sd_profit*3, y=-350, label = text_negative, color = "darkred") +
        geom_text(x=0+sd_profit*3, y=-350, label = text_positive , color = "darkgreen") +
        ggtitle(paste0("NPV distribution with mean = ",round(mean(df$NPV),0)))

grid.arrange(gg_total_profit, gg_total_profit_model, ncol = 1)
```


# Python applying

```{r}
library(reticulate)
use_condaenv("r-reticulate")
repl_python()
reticulate::py_config()
```
```{python}
import pandas as pd
import scipy as scipy 
import numpy as np 
import mpl_toolkits.axes_grid1.inset_locator as mpl_il 
import scipy.stats as st
from datetime import datetime
```

```{python}
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import MDS
from sklearn.manifold import TSNE
```
```{r}
df_profitPrAll_nona <- na.omit(df_profitPrAll)
df_profitPrAll_nona <- df_profitPrAll_nona[,!(names(df_profitPrAll_nona) %in% c(paste0("profit_mean_Next_",2:50)))]

X_profit_py <- df_profitPrAll_nona[,!(names(df_profitPrAll_nona) %in% c('date','profit'))]
Y_profit_py <- df_profitPrAll_nona[,(names(df_profitPrAll_nona) %in% c('profit'))]
date_profit_py <- df_profitPrAll_nona[,(names(df_profitPrAll_nona) %in% c('date'))]

colnames(df_profitPrAll_nona)
```


```{python}
X_profit = np.array(r.X_profit_py)
# Before applying PCA, each feature should be centered (zero mean) and with unit variance
X_normalized = StandardScaler().fit(X_profit).transform(X_profit)  



#mds = MDS(n_components = 2)
#X_mds = mds.fit_transform(X_normalized)

# tsne = TSNE(method='exact',n_components = 10)
# X_tsne = tsne.fit_transform(X_normalized)
# 
# pca = PCA(n_components = 2).fit(X_tsne)
# X_pca = pca.transform(X_tsne)
```
```{python}
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.preprocessing import MinMaxScaler

X_Scaler = MinMaxScaler().fit(X_profit).transform(X_profit)  

kmeans = KMeans(n_clusters = 10)
kmeans.fit(X_Scaler)

clusters = kmeans.labels_

cls = AgglomerativeClustering(n_clusters = 10)
cls_assignment = cls.fit_predict(X_Scaler)
```


```{r}
df <- as.data.frame(py$X_pca)
df$profit <- Y_profit_py
df$date <- date_profit_py
df$cluster <- py$cls_assignment

df %>%
  ggplot() +
  geom_point(aes(x = date, y = profit, color = as.factor(cluster)))# +
  #scale_color_gradient2(midpoint=0, limit = c(-2,2), space = "Lab",
  #                     low="red", mid="white", high="green")

df %>%
  group_by(cluster) %>%
  summarise(mp = mean(profit),
            n(),
            sum(profit)) %>%
  arrange(desc(mp),cluster)
```

```{python}
cls = AgglomerativeClustering(n_clusters = 15)
```

```{r}
for (index_end in 700:1488) {
X_profit_py <- df_profitPrAll_nona[1:index_end,!(names(df_profitPrAll_nona) %in% c('date','profit','predict_cl_profit'))]
Y_profit_py <- df_profitPrAll_nona[1:index_end,(names(df_profitPrAll_nona) %in% c('profit'))]
date_profit_py <- df_profitPrAll_nona[1:index_end,(names(df_profitPrAll_nona) %in% c('date'))]

py_run_string("X_profit = np.array(r.X_profit_py)")
py_run_string("X_Scaler = MinMaxScaler().fit(X_profit).transform(X_profit)")
py_run_string("cls_assignment = cls.fit_predict(X_Scaler)")

df <- data.frame('profit' = Y_profit_py,
                 'cluster' = py$cls_assignment)
index <- which(df$cluster == df[nrow(df),'cluster'])
df_profitPrAll_nona[index_end,'predict_cl_profit'] <- mean(df[index,"profit"])
}
```

```{r}
df_profitPrAll_nona %>%
  group_by(predict_cl_profit > 0) %>%
  summarise(mp = mean(profit),
            n(),
            sum(profit))
```

```{r}
df_profitPrAll_nona %>%
  ggplot() +
  geom_point(aes(x = date, y = profit, color = as.factor(predict_cl_profit > 0)))
```






































































